const XLSX = require("xlsx");

const data = [
  {
    "Company Name": "Shahi Exports",
    "HQ City": "Faridabad",
    "HQ State": "Haryana",
    "Latitude": 28.4089,
    "Longitude": 77.3178,
    "Year Founded": 1974,
    "Ownership Type": "Private",
    "Num Employees": 104340,
    "Num Male Workers": 29582,
    "Male %": 28.35,
    "Female": 74751,
    "Female %": 71.64,
    "Num Facilities": 52,
    "Reporting Standard": "Sustainability Report",
    "Reporting FY": "FY2023-24",
    "Scope1 tCO2e": 382577,
    "Scope2 LocationBased tCO2e": 57186,
    "Scope1 Plus 2 tCO2e": 439763,
    "RE Percentage": 65,
    "Total Energy TJ": 4334.23,
    "Solar Capacity MWp": 84,
    "Total Water KL": 4828552,
    "ZLD Coverage %": "Not Disclosed",
    "SBTi Status": "Not a member",
    "SBTi Engagement Opp": "HIGH",
    "CDP Score": "B",
    "ISO14001": "Certified",
    "GOTS": "Certified",
    "RE100 Member": "No",
    "Disclosure Quality": 3,
    "RE Ambition Score": 5,
    "Emissions Completeness": 2,
    "ESG Score": 67,
    "ESG Rating": "B",
    "Recommended Action": "Field meeting - pitch GHG calc + I-REC",
    "Sustainable Materials / Inputs %": 50,
    "Farmers Engaged": 52614,
    "Total Waste Generated (MT)": null,
    "Hazardous Waste (MT)": null,
    "Plastic Waste (MT)": null,
    "Renewable Energy Target": "100% RE by FY27",
    "Coal Phase-Out Status": "100% coal-free in garmenting",
    "Major Buyers": "Walmart, Gap Inc., Target, H&M, Nike, Uniqlo, PVH, Abercrombie & Fitch, C&A, Calvin Klein, Columbia Sportswear, Inditex, Kohl's",
    "Primary Raw Material": "Cotton Fabric, Polyester Fabric, Viscose, Denim, Trims",
    "Fabric Sourcing Geography": "India + China + Bangladesh + Vietnam + Turkey",
    "Employee Carbon Intensity (tCO₂e/employee/year)": 4.21,
    "Energy Carbon Intensity (tCO₂e/TJ)": 101.46
  },
  {
    "Company Name": "Vardhman Textiles",
    "HQ City": "Ludhiana",
    "HQ State": "Punjab",
    "Latitude": 30.901,
    "Longitude": 75.8573,
    "Year Founded": 1965,
    "Ownership Type": "Public Listed",
    "Num Employees": 27956,
    "Num Male Workers": 18345,
    "Male %": 65.62,
    "Female": 9611,
    "Female %": 34.38,
    "Num Facilities": 15,
    "Reporting Standard": "BRSR",
    "Reporting FY": "FY2023-24",
    "Scope1 tCO2e": 282924,
    "Scope2 LocationBased tCO2e": 857272.48,
    "Scope1 Plus 2 tCO2e": 1140196.48,
    "RE Percentage": 14.46,
    "Total Energy TJ": 12928,
    "Solar Capacity MWp": 19.2,
    "Total Water KL": 5695455.00,
    "ZLD Coverage %": "Not Disclosed",
    "SBTi Status": "Not found",
    "SBTi Engagement Opp": "HIGH",
    "CDP Score": "",
    "ISO14001": "Certified",
    "GOTS": "Certified",
    "RE100 Member": "No",
    "Disclosure Quality": 3,
    "RE Ambition Score": 3,
    "Emissions Completeness": 3,
    "ESG Score": 60,
    "ESG Rating": "B",
    "Recommended Action": "Outreach - pitch Scope 3 + I-REC marketplace",
    "Sustainable Materials / Inputs %": 28,
    "Farmers Engaged": null,
    "Total Waste Generated (MT)": 21423.87,
    "Hazardous Waste (MT)": 12459.58,
    "Plastic Waste (MT)": 1264.35,
    "Renewable Energy Target": "53 MW solar capacity by 2025",
    "Coal Phase-Out Status": "Transitioning boilers to biomass",
    "Major Buyers": "H&M, Gap, Banana Republic, Old Navy, Esprit, Benetton, Ford (special steels)",
    "Primary Raw Material": "Lint Cotton (primary), Organic Cotton, Better Cotton, Man-made Fibres",
    "Fabric Sourcing Geography": "India (Punjab, HP, MP) + limited global specialty fibres",
    "Employee Carbon Intensity (tCO₂e/employee/year)": 40.79,
    "Energy Carbon Intensity (tCO₂e/TJ)": 88.2
  },
  {
    "Company Name": "Arvind Limited",
    "HQ City": "Ahmedabad",
    "HQ State": "Gujarat",
    "Latitude": 23.0225,
    "Longitude": 72.5714,
    "Year Founded": 1931,
    "Ownership Type": "Public Listed",
    "Num Employees": 33311,
    "Num Male Workers": 23280,
    "Male %": 69.89,
    "Female": 10031,
    "Female %": 30.11,
    "Num Facilities": 12,
    "Reporting Standard": "BRSR + Integrated Annual Report",
    "Reporting FY": "FY2024-25",
    "Scope1 tCO2e": 253283,
    "Scope2 LocationBased tCO2e": 190808,
    "Scope1 Plus 2 tCO2e": 444091,
    "RE Percentage": 37,
    "Total Energy TJ": 6187.58,
    "Solar Capacity MWp": null,
    "Total Water KL": 2645994,
    "ZLD Coverage %": 83.33,
    "SBTi Status": "Committed",
    "SBTi Engagement Opp": "MEDIUM",
    "CDP Score": "",
    "ISO14001": "Certified",
    "GOTS": "Certified",
    "RE100 Member": "No",
    "Disclosure Quality": 4,
    "RE Ambition Score": 4,
    "Emissions Completeness": 4,
    "ESG Score": 80,
    "ESG Rating": "A",
    "Recommended Action": "Pitch market-based Scope 2 + I-REC + SBTi validation support",
    "Sustainable Materials / Inputs %": 37,
    "Farmers Engaged": 12000,
    "Total Waste Generated (MT)": 34493,
    "Hazardous Waste (MT)": 11765,
    "Plastic Waste (MT)": 762.2,
    "Renewable Energy Target": "40% RE by 2025",
    "Coal Phase-Out Status": "Biomass replacing coal",
    "Major Buyers": "Levi's, Gap Inc., H&M, American Eagle, Inditex, VF Corporation, Marks & Spencer, Calvin Klein, Hugo Boss, J.Crew, Mango, Banana Republic",
    "Primary Raw Material": "Cotton (BCI certified), Organic Cotton, Linen, Viscose, Modal, Tencel",
    "Fabric Sourcing Geography": "India: Gujarat (Ahmedabad, Naroda, Santej) + Bangladesh facility",
    "Employee Carbon Intensity (tCO₂e/employee/year)": 13.33,
    "Energy Carbon Intensity (tCO₂e/TJ)": 71.77
  },
  {
    "Company Name": "Trident Limited",
    "HQ City": "Barnala",
    "HQ State": "Punjab",
    "Latitude": 30.3819,
    "Longitude": 75.5468,
    "Year Founded": 1990,
    "Ownership Type": "Public Listed",
    "Num Employees": 15647,
    "Num Male Workers": 12850,
    "Male %": 82.12,
    "Female": 2797,
    "Female %": 17.88,
    "Num Facilities": 15,
    "Reporting Standard": "GRI + TCFD + UNGC + SASB + BRSR",
    "Reporting FY": "FY2023-24",
    "Scope1 tCO2e": 671774,
    "Scope2 LocationBased tCO2e": 347698,
    "Scope1 Plus 2 tCO2e": 1019472,
    "RE Percentage": 34.9,
    "Total Energy TJ": 10157,
    "Solar Capacity MWp": 40.9,
    "Total Water KL": 13724529,
    "ZLD Coverage %": "Not Disclosed",
    "SBTi Status": "Committed",
    "SBTi Engagement Opp": "LOW-MEDIUM",
    "CDP Score": "",
    "ISO14001": "Certified",
    "GOTS": "Certified",
    "RE100 Member": "No",
    "Disclosure Quality": 5,
    "RE Ambition Score": 4,
    "Emissions Completeness": 5,
    "ESG Score": 93,
    "ESG Rating": "A+",
    "Recommended Action": "Pitch I-REC retirement + coal phase-out timeline",
    "Sustainable Materials / Inputs %": 38.5,
    "Farmers Engaged": null,
    "Total Waste Generated (MT)": 251613,
    "Hazardous Waste (MT)": 4841,
    "Plastic Waste (MT)": 606,
    "Renewable Energy Target": "50% eng mix from RE (FY25)",
    "Coal Phase-Out Status": "41.3% biomass in fuel mix",
    "Major Buyers": "Ralph Lauren, Calvin Klein, JC Penney, IKEA, Target, Walmart, Macy's, Kohl's, Sam's Club, Burlington",
    "Primary Raw Material": "Cotton (BCI certified), Wheat Straw (paper), Yarn",
    "Fabric Sourcing Geography": "India: 95% domestic; Punjab + Madhya Pradesh (Barnala, Dhaula, Budhni)",
    "Employee Carbon Intensity (tCO₂e/employee/year)": 65.15,
    "Energy Carbon Intensity (tCO₂e/TJ)": 100.37
  }
];

const ws = XLSX.utils.json_to_sheet(data);
const wb = XLSX.utils.book_new();
XLSX.utils.book_append_sheet(wb, ws, "Company Profiles");

XLSX.writeFile(wb, "company_profiles_import.xlsx");
console.log("Successfully created company_profiles_import.xlsx in", __dirname);
